### ISSUE TITLE
Closing too fast Universal Manager crashes.

### ISSUE THREAD

**Issue by ghost** [Universal-Team/Universal-Manager#25] opened 2019-07-09 20:16 UTC
CONGRATULATIONS!!! YOU DID IT VOLTZ!!! :D After all your efforts, you managed to fix this crash that seemed impossible to fix. You did a good job! You deserve some cookies 🍪🍪🍪🍪

**Comment by SuperSaiyajinStackZ** [comment] 2019-07-09 20:20
Thanks for Posting this Issue! I will look into this Issue and I pin this for now. :)

**Comment by ghost** [comment] 2019-07-09 20:22
Thanks for looking into this!

**Comment by SuperSaiyajinStackZ** [comment] 2019-07-09 20:24
No problem! 😄

**Comment by SuperSaiyajinStackZ** [comment] 2019-07-20 22:26
This commit should fix the Crash. Can you try the latest Nightly when it is available and confirm? :) https://github.com/Universal-Team/Universal-Manager/commit/aef00130a2e96a4f45d557e12afc5c0c612c4d81

**Comment by SuperSaiyajinStackZ** [comment] 2019-07-20 23:21
It's finally fixed with the latest Commit! Thanks for Opening the Issue! 😛

**Comment by SuperSaiyajinStackZ** [comment] 2019-07-21 05:47
Hmm the last Commits seems to bring the Crash again. (Or maybe it wasn't even fixed? I'm not 100% sure though...)

This is the Debug Result : 

```
[New Thread 308]
Ignoring packet error, continuing...

Thread 5 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 308]
(gdb) bt
The current thread has terminated
(gdb) Exception condition detected on fd 612```

**Comment by SuperSaiyajinStackZ** [comment] 2019-07-24 01:13
A Crash happens now consistently after visiting the FileBrowse (But not the Scripts Screen) and then exiting the App through going to the MainMenu and then press Start or press Home and Close. 

This Issue is easy reproduceable.

I compiled it with an older devkitARM Version and it works fine.

An Image About the Debug Result is here : 

![Image](https://cdn.discordapp.com/attachments/589882205556310076/603353564504391713/unknown.png)

An Image from the 3DS (By Flame) is here : 

![Image](https://cdn.discordapp.com/attachments/589882205556310076/603392948549320774/image0.jpg)

**Comment by SuperSaiyajinStackZ** [comment] 2019-07-27 04:34
As of yet, I tried it already 2-3 Days to fix the Crash, but I don't get it fixed. I would appreciate any help! :)

**Comment by SuperSaiyajinStackZ** [comment] 2019-07-27 16:46
As of this commit : https://github.com/Universal-Team/Universal-Manager/commit/21aa7f8bf62aee7812f9e2e29e3749934642cd70

The Issue seems to be fixed for me. 

Can you confirm that? Just test with the latest Nightly. :)

**Comment by FlameKat53** [comment] 2019-08-19 16:17
Hi, @Javier107, does this still happen on the latest nightly of Universal-Manager?

**Comment by SuperSaiyajinStackZ** [comment] 2019-08-24 00:17
The screen-classes branch is done and this should be not an Issue anymore. But I Need a confirmation, so please test the latest Universal-Manager Nightly and tell me the result. Thank you.

**Comment by SuperSaiyajinStackZ** [comment] 2019-08-29 20:30
And the problem is fixed! :) I close this Issue now. 😛

**Closed as completed by SuperSaiyajinStackZ** 2019-08-29 20:30 UTC
Labels: bug, help wanted, High Priority
